const CATEGORIES = {
	All: 0,
	Arts_Entertainment: 3,
	Autos_Vehicles: 47,
	Beauty_Fitness: 44,
	Books_Literature: 22,
	Business_Industrial: 12,
	Computers_Electronics: 5,
	Finance: 7,
	Food_Drink: 71,
	Games: 8,
	Health: 45,
	Hobbies_Leisure: 65,
	Home_Garden: 11,
	Internet_Telecom: 13,
	Jobs_Education: 958,
	Law_Government: 19,
	News: 16,
	Online_Communities: 299,
	People_Society: 14,
	Pets_Animals: 66,
	Real_Estate: 29,
	Reference: 533,
	Science: 174,
	Shopping: 18,
	Sports: 20,
	Travel: 67,
}
module.exports = { CATEGORIES };